In [6]:
import pandas as pd

In [7]:
import numpy as np

In [8]:
data=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv",sep=";")

In [9]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [10]:
data.shape

(1599, 12)

In [13]:
pip install -U scikit-learn

Collecting scikit-learnNote: you may need to restart the kernel to use updated packages.

  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/5f/08/c66e99f06fb73f727c870172f0962c103262ac68839cc05234709b7b45c2/scikit_learn-1.3.0-cp38-cp38-win_amd64.whl.metadata
  Downloading scikit_learn-1.3.0-cp38-cp38-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.17.3 in d:\ineuron\project\mlflow\env\lib\site-packages (from scikit-learn) (1.24.4)
Collecting scipy>=1.5.0 (from scikit-learn)
  Using cached scipy-1.10.1-cp38-cp38-win_amd64.whl (42.2 MB)
Collecting joblib>=1.1.1 (from scikit-learn)
  Obtaining dependency information for joblib>=1.1.1 from https://files.pythonhosted.org/packages/10/40/d551139c85db202f1f384ba8bcf96aca2f329440a844f924c8a0040b6d02/joblib-1.3.2-py3-none-any.whl.metadata
  Downloading joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=2.0.0 (from scikit-learn)
  Obtaining dependency information for threadpoolctl>=2.0.0 from https://files.pythonhosted.org/packages/81/12/fd4dea011af9d69e1cad05c75f3f7202cdcbeac9b712eea58ca779a72865/threadpoolctl-3.2.0-py3-none-any.whl.metadata
  Downloading threadpoolctl-3.2.0-py3-none-any.whl.metadata (10.0 kB)
Using cached scikit_learn-1.3.0-cp38-cp38-win_amd64.whl (9.2 MB)
Downloading joblib-1.3.2-py3-none-any.whl (302 kB)
   ---------------------------------------- 0.0/302.2 kB ? eta -:--:--
   ---- ----------------------------------- 30.7/302.2 kB 1.4 MB/s eta 0:00:01
   ---- ----------------------------------- 30.7/302.2 kB 1.4 MB/s eta 0:00:01
   ----- --------------------------------- 41.0/302.2 kB 330.3 kB/s eta 0:00:01
   ---------- ---------------------------- 81.9/302.2 kB 353.1 kB/s eta 0:00:01
   ----------- --------------------------- 92.2/302.2 kB 403.5 kB/s eta 0:00:01
   -------------- ----------------------- 112.6/302.2 kB 386.4 kB/s eta 0:00:01
   ------------------ ------------------- 143.4/302.2 kB 405.9 kB/s eta 0:00:01
   ------------------------------ ------- 245.8/302.2 kB 580.1 kB/s eta 0:00:01
   ---------------------------------- --- 276.5/302.2 kB 550.1 kB/s eta 0:00:01
   ---------------------------------- --- 276.5/302.2 kB 550.1 kB/s eta 0:00:01
   ---------------------------------- --- 276.5/302.2 kB 550.1 kB/s eta 0:00:01
   -------------------------------------  297.0/302.2 kB 470.8 kB/s eta 0:00:01
   -------------------------------------- 302.2/302.2 kB 425.0 kB/s eta 0:00:00
Using cached threadpoolctl-3.2.0-py3-none-any.whl (15 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.3.2 scikit-learn-1.3.0 scipy-1.10.1 threadpoolctl-3.2.0

In [14]:
from sklearn.model_selection import train_test_split
train,test=train_test_split(data)

In [15]:
train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
21,7.6,0.390,0.31,2.30,0.082,23.0,71.0,0.99820,3.52,0.65,9.7,5
67,6.6,0.705,0.07,1.60,0.076,6.0,15.0,0.99620,3.44,0.58,10.7,5
1128,10.0,0.430,0.33,2.70,0.095,28.0,89.0,0.99840,3.22,0.68,10.0,5
1445,7.4,0.785,0.19,5.20,0.094,19.0,98.0,0.99713,3.16,0.52,9.6,6
627,8.8,0.600,0.29,2.20,0.098,5.0,15.0,0.99880,3.36,0.49,9.1,5
...,...,...,...,...,...,...,...,...,...,...,...,...
14,8.9,0.620,0.18,3.80,0.176,52.0,145.0,0.99860,3.16,0.88,9.2,5
1228,5.1,0.420,0.00,1.80,0.044,18.0,88.0,0.99157,3.68,0.73,13.6,7
1057,7.6,0.420,0.25,3.90,0.104,28.0,90.0,0.99784,3.15,0.57,9.1,5
381,13.7,0.415,0.68,2.90,0.085,17.0,43.0,1.00140,3.06,0.80,10.0,6
721,8.9,0.480,0.24,2.85,0.094,35.0,106.0,0.99820,3.10,0.53,9.2,5

In [16]:
test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1391,8.0,0.640,0.22,2.4,0.094,5.0,33.0,0.99612,3.37,0.58,11.00,5
831,5.9,0.610,0.08,2.1,0.071,16.0,24.0,0.99376,3.56,0.77,11.10,6
1395,8.6,0.685,0.10,1.6,0.092,3.0,12.0,0.99745,3.31,0.65,9.55,6
6,7.9,0.600,0.06,1.6,0.069,15.0,59.0,0.99640,3.30,0.46,9.40,5
299,6.9,0.670,0.06,2.1,0.080,8.0,33.0,0.99845,3.68,0.71,9.60,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1497,6.9,0.740,0.03,2.3,0.054,7.0,16.0,0.99508,3.45,0.63,11.50,6
1473,6.1,0.600,0.08,1.8,0.071,14.0,45.0,0.99336,3.38,0.54,11.00,5
959,8.0,0.590,0.05,2.0,0.089,12.0,32.0,0.99735,3.36,0.61,10.00,5
503,10.5,0.260,0.47,1.9,0.078,6.0,24.0,0.99760,3.18,1.04,10.90,7
243,15.0,0.210,0.44,2.2,0.075,10.0,24.0,1.00005,3.07,0.84,9.20,7

In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import ElasticNet

from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score,accuracy_score,roc_auc_score
from sklearn.model_selection import  train_test_split

In [18]:
X_train=train.drop(["quality"],axis=1)
X_test=test.drop(["quality"],axis=1)

In [19]:
y_train=train[["quality"]]
y_test=test[["quality"]]

In [20]:
y_train

      quality
21          5
67          5
1128        5
1445        6
627         5
...       ...
14          5
1228        7
1057        5
381         6
721         5

[1199 rows x 1 columns]

In [21]:
y_test

      quality
1391        5
831         6
1395        6
6           5
299         5
...       ...
1497        6
1473        5
959         5
503         7
243         7

[400 rows x 1 columns]

In [22]:
X_train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
21,7.6,0.390,0.31,2.30,0.082,23.0,71.0,0.99820,3.52,0.65,9.7
67,6.6,0.705,0.07,1.60,0.076,6.0,15.0,0.99620,3.44,0.58,10.7
1128,10.0,0.430,0.33,2.70,0.095,28.0,89.0,0.99840,3.22,0.68,10.0
1445,7.4,0.785,0.19,5.20,0.094,19.0,98.0,0.99713,3.16,0.52,9.6
627,8.8,0.600,0.29,2.20,0.098,5.0,15.0,0.99880,3.36,0.49,9.1
...,...,...,...,...,...,...,...,...,...,...,...
14,8.9,0.620,0.18,3.80,0.176,52.0,145.0,0.99860,3.16,0.88,9.2
1228,5.1,0.420,0.00,1.80,0.044,18.0,88.0,0.99157,3.68,0.73,13.6
1057,7.6,0.420,0.25,3.90,0.104,28.0,90.0,0.99784,3.15,0.57,9.1
381,13.7,0.415,0.68,2.90,0.085,17.0,43.0,1.00140,3.06,0.80,10.0
721,8.9,0.480,0.24,2.85,0.094,35.0,106.0,0.99820,3.10,0.53,9.2

In [23]:
X_test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
1391,8.0,0.640,0.22,2.4,0.094,5.0,33.0,0.99612,3.37,0.58,11.00
831,5.9,0.610,0.08,2.1,0.071,16.0,24.0,0.99376,3.56,0.77,11.10
1395,8.6,0.685,0.10,1.6,0.092,3.0,12.0,0.99745,3.31,0.65,9.55
6,7.9,0.600,0.06,1.6,0.069,15.0,59.0,0.99640,3.30,0.46,9.40
299,6.9,0.670,0.06,2.1,0.080,8.0,33.0,0.99845,3.68,0.71,9.60
...,...,...,...,...,...,...,...,...,...,...,...
1497,6.9,0.740,0.03,2.3,0.054,7.0,16.0,0.99508,3.45,0.63,11.50
1473,6.1,0.600,0.08,1.8,0.071,14.0,45.0,0.99336,3.38,0.54,11.00
959,8.0,0.590,0.05,2.0,0.089,12.0,32.0,0.99735,3.36,0.61,10.00
503,10.5,0.260,0.47,1.9,0.078,6.0,24.0,0.99760,3.18,1.04,10.90
243,15.0,0.210,0.44,2.2,0.075,10.0,24.0,1.00005,3.07,0.84,9.20

In [25]:
rf=RandomForestClassifier()
rf.fit(X_train, y_train)

d:\Ineuron\Project\mlflow\env\lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier()

In [26]:
X_test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
1391,8.0,0.640,0.22,2.4,0.094,5.0,33.0,0.99612,3.37,0.58,11.00
831,5.9,0.610,0.08,2.1,0.071,16.0,24.0,0.99376,3.56,0.77,11.10
1395,8.6,0.685,0.10,1.6,0.092,3.0,12.0,0.99745,3.31,0.65,9.55
6,7.9,0.600,0.06,1.6,0.069,15.0,59.0,0.99640,3.30,0.46,9.40
299,6.9,0.670,0.06,2.1,0.080,8.0,33.0,0.99845,3.68,0.71,9.60
...,...,...,...,...,...,...,...,...,...,...,...
1497,6.9,0.740,0.03,2.3,0.054,7.0,16.0,0.99508,3.45,0.63,11.50
1473,6.1,0.600,0.08,1.8,0.071,14.0,45.0,0.99336,3.38,0.54,11.00
959,8.0,0.590,0.05,2.0,0.089,12.0,32.0,0.99735,3.36,0.61,10.00
503,10.5,0.260,0.47,1.9,0.078,6.0,24.0,0.99760,3.18,1.04,10.90
243,15.0,0.210,0.44,2.2,0.075,10.0,24.0,1.00005,3.07,0.84,9.20

In [27]:
pred_prob=rf.predict_proba(X_test)

In [28]:
roc_auc_score=roc_auc_score(y_test,pred_prob,multi_class='ovr')

In [29]:
roc_auc_score

0.7769781833782634